"""fix

Revision ID: e770b4b6116f
Revises: 7f393ad40cee
Create Date: 2025-04-08 21:07:18.748848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e770b4b6116f'
down_revision: Union[str, None] = '7f393ad40cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='date::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
